# Generated by Django 2.2.2 on 2019-06-13 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_room', '0003_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_message',
            field=models.DateTimeField(default=None, verbose_name='last message'),
        ),
    ]
